### ISSUE TITLE
无法捕获 Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR) 异常

### ISSUE THREAD

**Issue by enigmkk** [BAByte/NativeCrash2Java#2]
void Crash() {
//    volatile int *a = (int *) nullptr;
//    *a = 1;
    char *szChar = 0;
    strcpy(szChar, "fasdflasdfasdfasdfa");
}
 Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 28922 (DefaultDispatch), pid 28839 (e.banativecrash)

**Comment by BAByte** [comment]
@konekwok 给出的是可以复现的示例代码吗？

**Comment by BAByte** [comment]
@konekwok 我这边测试，是可以捕获到的：
<img width="1381" alt="image" src="https://user-images.githubusercontent.com/26603853/221795132-4dedb1e8-80f4-48ed-83da-18d7cdc3bb35.png">

**Comment by BAByte** [comment]
因问题方暂未提供更多信息，先关闭该问题
