### ISSUE TITLE
感谢作者给出思路和代码。请问这个方案可以带到线上吗？

### ISSUE THREAD

**Issue by sy007** [BAByte/NativeCrash2Java#3]

**Comment by BAByte** [comment]
> 
@sy007 不保证，我在国内各大品牌的机型验证过，可以正常工作

**Comment by BAByte** [comment]
不保证，我在国内各大品牌的机型验证过，可以正常工作

**Comment by sy007** [comment]
> 不保证，我在国内各大品牌的机型验证过，可以正常工作

好的。谢谢，你们项目中用了这个方案了吗？

**Comment by BAByte** [comment]
> 好的。谢谢，你们项目中用了这个方案了吗？
@sy007 
有的
